version: '3.8'
services:
    flask:
        build: ./flask
        container_name: flask
        restart: always
        expose:
          - 8080
        depends_on: 
            - db
    
    db:
        image: mysql:5.7.22
        restart: always
        environment: 
            MYSQL_DATABASE: doctor_appointment
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 33067:3306

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"        