"""empty message

Revision ID: 6e485b682d29
Revises: 1bf537b90c39
Create Date: 2021-09-14 04:05:09.937010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e485b682d29'
down_revision = '1bf537b90c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointment', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'appointment', 'patient', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointment', type_='foreignkey')
    op.drop_column('appointment', 'patient_id')
    # ### end Alembic commands ###
